name: Converter Pipeline

on:
  push:
    branches:
      - main

jobs:

  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26"

      - name: Download dependencies
        run: go mod download

      - name: Run Go tests
        run: go test ./...

      - name: Build Go project
        run: go build ./...


  build-project:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26"

      - name: Download dependencies
        run: go mod download

      - name: Build
        run: go build -o app ./server


  docker:
    needs: build-project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t hadi3eh/converter:v1 .

      - name: Push Docker image
        run: docker push hadi3eh/converter:v1


  deploy:
    name: Deploy to Server
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull hadi3eh/converter:v1

            docker stop converter || true
            docker rm converter || true

            docker run -d \
              --name converter \
              --restart unless-stopped \
              -p 8080:8080 \
              hadi3eh/converter:v1